### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by jeremyjh** [gabrielgatu/mix-dialyzer#3]
So it looks like [this commit](https://github.com/gabrielgatu/mix-dialyzer/commit/ffc814a1a7db61c37bbc82d09ae1bd1e2d6498fa) imported several thousand lines of code from [dialyxir](https://github.com/jeremyjh/dialyxir), but not the copyright notice. Dialyxir is released under the Apache 2.0 license, and you are free to use it's code. However if you do so, you need to comply with the license and reproduce the copyright notice in the `LICENSE` file. Note that this is true even if you refactor and change the code; thats still a derivative work.

Also in this case it looks like what you are interested in is the parser, pretty printing and warning documentation. This was all developed quite recently by Andrew Summers (@asummers). I think if you are going to use this, and particularly if it is going to be incorporated into the elixir org at some point, he should be specifically attributed for those files. In the dialyxir repo, everyone can see who authored them, but at isn't the case here.

Also one other note, purely technical: you checked in the erlang code built by `yecc`. Since those are build artifacts, they should be in your .gitignore. Only the `.xrl` and `.yrl` files are needed in your repo and hex distribution.

**Comment by gabrielgatu** [comment]
Thanks for your feedback Jeremy :heart::heart::heart:

I've updated all the necessary files with a credit section at the top, and used the same Apache 2 license of dialyxir

Some days ago I've spoken also with Andrew, and he told me that he would like to extract the code into a library, so that multiple projects can benefit from it, it could be really nice, both for dialyxir and for mix-dialyzer, since we could both contribute and benefit from the same source code.

Also, you can have a more detailed look of all the things currently implemented in mix-dialyzer and their history [here](https://github.com/gabrielgatu/mix-dialyzer/tree/master/doc).

Just let me know if there is something else that needs to be changed. Every feedback is always welcomed! :blush:

**Comment by jeremyjh** [comment]
Looks good, thanks!
